# Generated by Django 5.2 on 2025-04-09 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_id', models.CharField(max_length=50)),
                ('detection_type', models.CharField(choices=[('PPE', 'PPE'), ('FIRE', 'Fire')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('result_json', models.JSONField()),
            ],
        ),
    ]
